# Use the official Nginx image
FROM nginx:alpine

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy the Nginx configuration from your project
COPY nginx.conf /etc/nginx/conf.d
COPY certs /etc/nginx/certs
EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
