# Generated by Django 5.0.4 on 2024-04-15 20:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('latest_team', models.CharField(default='', max_length=100)),
                ('first_year_recorded', models.IntegerField(default=2001, validators=[django.core.validators.MinValueValidator(2001), django.core.validators.MaxValueValidator(2023)])),
                ('last_year_recorded', models.IntegerField(default=2001, validators=[django.core.validators.MinValueValidator(2001), django.core.validators.MaxValueValidator(2023)])),
                ('default_cybercoach_filename', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Coach',
                'verbose_name_plural': 'Coaches',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Cybercoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('DECISION_TREE', 0), ('RANDOM_FOREST', 1), ('KNN', 2), ('LOGISTIC_REGRESSION', 3), ('MLP_NN', 4)], max_length=100)),
                ('model_filename', models.CharField(default='', max_length=100)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pygskin_webapp.coach')),
            ],
            options={
                'verbose_name': 'Cybercoach',
                'verbose_name_plural': 'Cybercoaches',
                'ordering': ['coach', 'model_type'],
            },
        ),
    ]
