# Generated by Django 5.0.4 on 2024-05-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygskin_webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('reason_for_subscribing', models.CharField(choices=[('CFB', 'Interested in college football'), ('TECH', 'Interested in the technology'), ('OTHER', 'Other')], default='CFB', max_length=50)),
                ('identity', models.CharField(choices=[('FAN', 'Fan of college football'), ('STUDENT', 'Student'), ('COACH_PLAYER', 'Football coach or player'), ('OTHER', 'Other')], default='FAN', max_length=50)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
