# Generated by Django 5.0.4 on 2024-10-10 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygskin_webapp', '0003_coach_biography'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='email_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
