# Generated by Django 5.0.4 on 2024-11-07 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygskin_webapp', '0004_subscriber_email_updates_subscriber_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfbdb_game_id', models.IntegerField()),
                ('season', models.IntegerField()),
                ('week', models.IntegerField()),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('home_money_line', models.IntegerField(blank=True, null=True)),
                ('away_money_line', models.IntegerField(blank=True, null=True)),
                ('spread', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('over_under', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('game_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(max_length=50)),
                ('credits_bet', models.IntegerField()),
                ('odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bet_placed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('payout', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pygskin_webapp.game')),
            ],
        ),
        migrations.CreateModel(
            name='BettingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=20)),
                ('credits_adjusted', models.IntegerField()),
                ('balance_after_transaction', models.IntegerField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('bet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pygskin_webapp.bet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_score', models.IntegerField(default=0)),
                ('away_team_score', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pygskin_webapp.game')),
            ],
        ),
        migrations.CreateModel(
            name='UserCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_credits', models.IntegerField(default=10000)),
                ('credits_won', models.IntegerField(default=0)),
                ('credits_lost', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
