# Generated by Django 5.0.4 on 2024-11-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygskin_webapp', '0005_game_bet_bettingtransaction_gamescore_usercredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_money_line',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_money_line',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
