# Generated by Django 5.0.4 on 2024-11-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygskin_webapp', '0006_alter_game_away_money_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
