# Generated by Django 5.0.4 on 2024-11-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygskin_webapp', '0007_alter_game_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='over_under_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='spread_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
