# Generated by Django 5.0.4 on 2024-11-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygskin_webapp', '0008_game_over_under_price_game_spread_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='over_under_price',
        ),
        migrations.RemoveField(
            model_name='game',
            name='spread_price',
        ),
        migrations.AddField(
            model_name='game',
            name='away_over_under_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='away_spread_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='home_over_under_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='home_spread_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
