# Generated by Django 5.0.4 on 2025-01-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygskin_webapp', '0011_alter_usercredit_total_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='file_hash',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
    ]
