# Generated by Django 5.0.4 on 2025-01-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygskin_webapp', '0012_coach_file_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='file_hash',
        ),
        migrations.AddField(
            model_name='cybercoach',
            name='file_hash',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
    ]
