name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}
  SECRET_KEY: ${{ secrets.django_secret_key }}
  DEBUG: "TRUE"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pygskin-webapp:$(date +%s)
